sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
  - "10"
  - "11"

jobs:
  include:
    - stage: test
      before_install:
        - echo "before install $(node -v)"
      install:
        - echo "install $(node -v)"
      script:
        - echo "script $(node -v)"
      after_success:
        - echo "after success $(node -v)"
    - stage: release 1
      deploy:
        provider: script
        script: echo "release 1 deploy script"
    - stage: release 22
      deploy:
        provider: script
        script: echo "release 22 deploy script"

