sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
  - "10"
  - "11"

before_install:
  - echo "before install $(node -v)"
install:
  - echo "install $(node -v)"
script:
  - echo "script $(node -v)"
  - echo foobar > foobar
  - git add -A
  - |
    if [[ $(git status --porcelain) ]]; then
      git config user.name "travis"
      git config user.email "build@travis-ci.com"
      git commit -m 'chore(build):changes from build'
    fi
after_success:
  - echo "after success $(node -v)"

jobs:
  include:
    - stage: release 1
      node_js: "10"
      if: type = push AND branch = master
      script: skip
      deploy:
        provider: script
        script: echo "release 1 deploy script"
    - stage: release 22
      node_js: "10"
      if: type = push AND tag IS present
      script: skip
      deploy:
        provider: script
        script: echo "release 22 deploy script"

