sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
  - "10"
  - "11"

before_install:
  - echo "before install $(node -v)"
install:
  - echo "install $(node -v)"
script:
  - echo "script $(node -v)"
after_success:
  - echo "after success $(node -v)"

jobs:
  include:
    - stage: release 1
      script: skip
      deploy:
        provider: script
        script: echo "release 1 deploy script"
    - stage: release 22
      script: skip
      deploy:
        provider: script
        script: echo "release 22 deploy script"

